sudo: required
services:
  - docker

before_install:
  - docker build -t dennisdurairaj/docker-react -f Dockerfile.dev .

script:
  - docker run rm dennisdurairaj/docker-react /bin/sh -c "CI=true npm run test"