sudo: required
services:
  - docker

before_install:
  - docker build -t dennisdurairaj/docker-react -f Dockerfile.dev .

script:
  - docker run --rm dennisdurairaj/docker-react /bin/sh -c "CI=true npm run test"

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact.env"
  bucket_name: "elasticbeanstalk-us-east-2-253763785936"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
